name = "chatgpt-api"
main = "src/index.js"
compatibility_date = "2023-03-03"
usage_model = "bundled"
env = { }
kv_namespaces = [
  { binding = "kv", id = "188fab546f5b4569a07ae1a15a22aaf6" }
]

[triggers]
crons = [ ]
